### PR TITLE
DoRA support

### PR DESCRIPTION
**Pull request by catboxanon**
Title. Adapted from https://github.com/comfyanonymous/ComfyUI/commit/ae77590b4e0cbab55ac9edb67722092d375fe3ec

---

Semi-related: I don't think my question I originally asked in https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/80 was addressed well. Are we planning to sync upstream of both the webui _and_ ComfyUI? Or, only the webui, and to cherry-pick certain updates from ComfyUI such as this one?

### CODE REVIEW

**Comment by GavChap** [comment]
I've checked this locally by pulling the request branch and it works fine, will this be merged at any point?

**Review by abel1502 — APPROVED** [review]

**Comment by ntc-ai** [comment]
Hi, this matches ComfyUI but differs from sdwebui. The generated image changes at scale 0. I opened a patch to ComfyUI to try to standardize on sdwebui's approach:
https://github.com/comfyanonymous/ComfyUI/pull/3298

**Comment by kleineluka** [comment]
@catboxanon can you change this pr to dev2 and could @huchenlei merge? seems like main is dead for now

**Review by Bluenochian — APPROVED** [review]

**Review by lllyasviel — APPROVED** [review]

**Comment by lllyasviel** [comment]
hi we are going to close PRs before forge's recent major revision
if we missed some important PRs, please consider reopen (if that is not already on our todo list

**Pull request closed without merging**
