### PR TITLE
Add back ControlNet multi-inputs upload tab

### PR DESCRIPTION
**Pull request by huchenlei**
## Description
Closes https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/98

IP-Adapter face_id and photomaker verified to be working with multi-inputs.
InstantID not working with multi-inputs now. @lllyasviel PTAL if we can somehow make multi-inputs work for InstantID. In sd-webui-controlnet, the approach is approximation via averaging the insightface embedding.

## Screenshots/videos:
image

## Checklist:

- [ ] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [ ] I have performed a self-review of my own code
- [ ] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ ] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by strawberrymelonpanda** [comment]
@huchenlei Functionality works great, but I did notice that if I upload an image that is taller than it is wide, on Chromium at least, the upload area overlaps with the control boxes below.  This doesn't happen with wide images.

image

**Comment by lllyasviel** [comment]
this will be taken a look later since it needs more considerations

**Comment by StellarBeing25** [comment]
> this will be taken a look later since it needs more considerations

Please move the Batch Folder and Batch Upload together under a Batch tab and restore the Multi Input tab to avoid confusion. It is very important for IP Adapters like FaceID Portrait which requires 5 input images.

**Comment by a3nima** [comment]
> > this will be taken a look later since it needs more considerations
> 
> Please move the Batch Folder and Batch Upload together under a Batch tab and restore the Multi Input tab to avoid confusion. It is very important for IP Adapters like FaceID Portrait which requires 5 input images.

also my (and many others) ip adapter face id workflow requires a set of image as base. maybe multi show multi-input only, where it actually works -if that's the problem?

**Comment by strawberrymelonpanda** [comment]
I've been using the PR - it works great, exactly as expected.  Please consider merging this soon.

**Comment by saunderez** [comment]
Like to also report this PR is working great in conjunction with Face ID IP Adaptor, greatly improved likeness using multiple source images.

**Comment by ScionoicS** [comment]
Was trying to use instant id today when i noticed I was unable to use multiple image inputs like I can on the regular controlnet extension.  

Why remove?

**Comment by strawberrymelonpanda** [comment]
@sohamaa in #344 raises a valid point: The "Multiple Images" tab is even shown in the screenshots of the README.

image

**Comment by CRCODE22** [comment]
Nobody in their right mind would remove the multi inputs feature. It is a feature many including me want to use. On top of that forge does not allow you to use the main branch of control net only the build in. So I am going back to automatic 1111 where I am allowed to use the not restricted controlnet.

**Comment by CRCODE22** [comment]
I added it back to my own installation.

**Comment by saunderez** [comment]
> > I added it back to my own installation.
> > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> 
> I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> 
> I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> 
> Thank you
Everything you need to know is at the link below.

https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files

**Comment by CRCODE22** [comment]
> > I added it back to my own installation.
> > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> 
> I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> 
> I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> 
> Thank you

These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files



Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.

**Comment by JaB43a** [comment]
> > > I added it back to my own installation.
> > > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> > 
> > 
> > I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> > I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> > Thank you
> 
> These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files
> 
> 
> 
> Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.

I have tried it, but it doesn't work. At least in my case.
Although I upload several images, the end result is that it only takes one of them (testing with the same config and seed, the results are the same, the same face appears)

Thank you anyway

**Comment by CRCODE22** [comment]
> > > > I added it back to my own installation.
> > > > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> > > 
> > > 
> > > I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> > > I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> > > Thank you
> > 
> > 
> > These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files
> > 
> > Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.
> 
> I have tried it, but it doesn't work. At least in my case. Although I upload several images, the end result is that it only takes one of them (testing with the same config and seed, the results are the same, the same face appears)
> 
> Thank you anyway :)

When using photomaker are you making sure your positive prompt does not exceed 75 tokens? I noticed once you go past that photomaker will not generate faces.

**Comment by ut1kaa** [comment]
```
*** Error running process_before_every_sampling: D:\Work\DIffusion\custom-forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\Work\DIffusion\custom-forge\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\Work\DIffusion\custom-forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Work\DIffusion\custom-forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 566, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
      File "D:\Work\DIffusion\custom-forge\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Work\DIffusion\custom-forge\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 512, in process_unit_before_every_sampling
        params.model.process_before_every_sampling(p, cond, mask, *args, **kwargs)
      File "D:\Work\DIffusion\custom-forge\webui\extensions-builtin\sd_forge_photomaker\scripts\forge_photomaker.py", line 51, in process_before_every_sampling
        cond_modified = opPhotoMakerEncode(photomaker=self.model, image=cond.movedim(1, -1), clip=clip, text=text)[0]
    AttributeError: 'dict' object has no attribute 'movedim'
``` 
When using Photomaker this error occurs, is there any solution? The image is generated but the face is not used.

**Comment by JaB43a** [comment]
> > > > > I added it back to my own installation.
> > > > > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> > > > 
> > > > 
> > > > I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> > > > I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> > > > Thank you
> > > 
> > > 
> > > These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files
> > > 
> > > Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.
> > 
> > 
> > I have tried it, but it doesn't work. At least in my case. Although I upload several images, the end result is that it only takes one of them (testing with the same config and seed, the results are the same, the same face appears)
> > Thank you anyway :)
> 
> When using photomaker are you making sure your positive prompt does not exceed 75 tokens? I noticed once you go past that photomaker will not generate faces.
> 
> Here it does work:
> 
> Moving model(s) has taken 0.68 seconds 2024-02-27 04:00:06,151 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,422 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,620 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,833 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:07,188 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:07,650 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. To load target model SDXL

I haven't used Photomaker much, the one I use is InstantID, and it is with InstantID that it doesn't work.

**Comment by banjaminicc** [comment]
Please consider the merge, it is extremely useful for FaceID ipadapter and InstantID

> > > > > > I added it back to my own installation.
> > > > > > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> > > > > 
> > > > > 
> > > > > I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> > > > > I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> > > > > Thank you
> > > > 
> > > > 
> > > > These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files
> > > > 
> > > > Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.
> > > 
> > > 
> > > I have tried it, but it doesn't work. At least in my case. Although I upload several images, the end result is that it only takes one of them (testing with the same config and seed, the results are the same, the same face appears)
> > > Thank you anyway :)
> > 
> > 
> > When using photomaker are you making sure your positive prompt does not exceed 75 tokens? I noticed once you go past that photomaker will not generate faces.
> > Here it does work:
> > Moving model(s) has taken 0.68 seconds 2024-02-27 04:00:06,151 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,422 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,620 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:06,833 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:07,188 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. Moving model(s) skipped. Cleanup has taken 0.00 seconds 2024-02-27 04:00:07,650 - ControlNet - INFO - ControlNet Method ClipVision (Photomaker) patched. To load target model SDXL
> 
> I haven't used Photomaker much, the one I use is InstantID, and it is with InstantID that it doesn't work.

It is working for me with InstantID though

**Comment by webinksupport** [comment]
Multi-image tab doesn't seem to work on inpainting (possibly all of img2img).

**Comment by a3nima** [comment]
> this will be taken a look later since it needs more considerations

why is it not implented yet?

**Comment by lhucklen** [comment]
Please implement, this is such a good quality of life setting

**Comment by PeanutButterSkeletonCrew** [comment]
I would also like to see this re-implemented. I'm very surprised it was removed in the first place.

**Comment by a3nima** [comment]
> > > I added it back to my own installation.
> > > Thank you @huchenlei for making the changes it is as simple as overwriting 5 files.
> > 
> > 
> > I'm very interested in knowing how you did it. What files did you change and what did you change about each of them.
> > I also join the request that this option be officially present again, it is very useful for me to generate certain characters that I can only generate with different images.
> > Thank you
> 
> These 5 files from here https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/264/files
> 
> 
> 
> Overwrite the files in your local installation and it will work at least when I tested it 5 days ago and have not updated Forge since.

While this still works, it would be nice to have the multi upload function AND the "use mask" function working together. I have to switch to single image to get the mask drawing/use mask feature atm. which makes them unusable together.

**Comment by lhucklen** [comment]
Any updates on this? @lllyasviel

**Comment by a3nima** [comment]
Btw I've found that with the code provided by @huchenlei I do get an error, when trying to use controlnet inpaint. multi-inputs for ip-adapter still works though.

**Comment by gohan2091** [comment]
I really need multiple inputs for Face ID. Really hope this can be added back.

**Comment by strawberrymelonpanda** [comment]
> huchenlei merged commit 61a2a9d into lllyasviel:dev2

I've been asking for this pretty much since Forge launched, ha.  Thanks @huchenlei!👍

**Comment by GatorsUF** [comment]
> > huchenlei merged commit [61a2a9d](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/61a2a9d342c047056c06a83221934fb9407f327a) into lllyasviel:dev2
> 
> I've been asking for this pretty much since Forge launched, ha. Thanks @huchenlei!👍

I just tried it on dev2 branch and I can't get controlnet/ipadapter to work with multi-inputs. In fact I can't get ipadapter to work at all on the dev2 branch even with a single image input.

**Comment by tealytee** [comment]
i get this error

*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "G:\SD F\sd forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\SD F\sd forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\SD F\sd forge\webui\extensions-builtin\sd_forge_controlnet1\scripts\controlnet.py", line 15, in <module>
        from lib_controlnet.utils import (
      File "G:\SD F\sd forge\webui\extensions-builtin\sd_forge_controlnet1\lib_controlnet\utils.py", line 9, in <module>
        from modules_forge.forge_util import HWC3
    ModuleNotFoundError: No module named 'modules_forge.forge_util'

**Comment by NeiroNext** [comment]
The error is still present, where can I find out the status of its fix?

**Comment by Desu21212** [comment]
Hello. This was a very good thing to have. It's better than an actual lora. SD. 1.5 just wins over forge in face ID department because of the the multi-upload. You have to add it back please!

**Comment by a3nima** [comment]
> Hello. This was a very good thing to have. It's better than an actual lora. SD. 1.5 just wins over forge in face ID department because of the the multi-upload. You have to add it back please!

I dont think Illyasviel will add it back, because it's somewho not a clean method. But you can use 2 Controlnets with 1 image each and adjust the weights to "mix" faces in forge.

**Comment by Esperontre** [comment]
> I dont think Illyasviel will add it back, because it's somehow not a technically clean method. But you can use 2 Controlnets with 1 image each and adjust the weights to "mix" faces in forge.

Is there a way for more than 3 images? Multi-controlnet input was useful for my end as I used IP-Adapter to toss in 5 images of armor in order to produce quick armor combinations, rather than individually changing the image per controlnet which can cause time to pile up if multiple combos are being tested.

**Comment by a3nima** [comment]
yeah, there are other reasons (the one you called and also (probably?!) less cpu/ram ressources needed with just 1controlnet active)  for adding it back somehow. I've had added it back with some change of code that was provided in the github posts, but I dont think that works anymore.

**Pull request merged**
