### PR TITLE
implement align your steps scheduler

### PR DESCRIPTION
**Pull request by blob42**
Signed-off-by: blob42 <contact@blob42.xyz>

## Description

implement [Align Your Steps](https://research.nvidia.com/labs/toronto-ai/AlignYourSteps/) scheduler.

Credit to this [PR](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15751) which I used as base.

### SDXL

xyz_grid-0012-3839149266

xyz_grid-0011-3839149266

### SD1.5

xyz_grid-0019-1792503894

## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [x] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by dan4ik94** [comment]
@huchenlei would you merge this please, when you have time.

**Comment by Panchovix** [comment]
Is there a way to add Restart sampler with this scheduler?

**Comment by dan4ik94** [comment]
> Is there a way to add Restart sampler with this scheduler?

append to the samplers array in **forge_alter_samplers.py**, should do the trick
`sd_samplers_common.SamplerData('Restart AYS', build_constructor(sampler_name='restart', scheduler_name='ays'), ['restart_ays'], {}),`

**Review by huchenlei — APPROVED** [review]

**Comment by Panchovix** [comment]
@dan4ik94 
> > Is there a way to add Restart sampler with this scheduler?
> 
> append to the samplers list in **forge_alter_samplers.py**, should do the trick
> 
> `sd_samplers_common.SamplerData('Restart AYS', build_constructor(sampler_name='restart', scheduler_name='ays'), ['restart_ays'], {}),`
> 
> remJc7DvaO

Restart AYS doesn't seem to work sadly.

**Comment by Koitenshin** [comment]
AYS can look much better than what you have here but someone else needs to do the programming. I tried on my own installation of A1111 but couldn't figure out how.

We need to take the 14.615 sigma and automatically stretch it out over the amount of total steps the user selects.
It's extremely rudimentary downsloping but I used the following sigmas for 32 steps (complex prompts require more steps).
My image turned out much better using 32 sigmas over 32 steps than 11 sigmas over 32 steps.

sigmas = [14.615, 14.158, 13.702, 13.245, 12.788, 12.331, 11.875, 11.418, 10.961, 10.505, 10.048, 9.591, 9.134, 8.678, 8.221, 7.764, 7.308, 6.851, 6.394, 5.937, 5.481, 5.024, 4.567, 4.110, 3.654, 3.197, 2.740, 2.284, 1.827, 1.370, 0.913, 0.457, 0]

**Comment by blob42** [comment]
@Koitenshin I will do some experiments and improved implementation when I have some free time

**Comment by blob42** [comment]
@Koitenshin I am not well versed in the math behind sampling schedulers I merely ported the existing A1111 implantation here. It looks like Comfy also is used the same algorithm.

 Could you explain the heuristic  used to stretch the sigmas over the steps ?

**Comment by dan4ik94** [comment]
> AYS can look much better than what you have here but someone else needs to do the programming. I tried on my own installation of A1111 but couldn't figure out how.
> 
> We need to take the 14.615 sigma and automatically stretch it out over the amount of total steps the user selects. It's extremely rudimentary downsloping but I used the following sigmas for 32 steps (complex prompts require more steps). My image turned out much better using 32 sigmas over 32 steps than 11 sigmas over 32 steps.
> 
> sigmas = [14.615, 14.158, 13.702, 13.245, 12.788, 12.331, 11.875, 11.418, 10.961, 10.505, 10.048, 9.591, 9.134, 8.678, 8.221, 7.764, 7.308, 6.851, 6.394, 5.937, 5.481, 5.024, 4.567, 4.110, 3.654, 3.197, 2.740, 2.284, 1.827, 1.370, 0.913, 0.457, 0]

can you show some image examples with 11 and 32 sigmas

**Comment by Koitenshin** [comment]
> @Koitenshin I am not well versed in the math behind sampling schedulers I merely ported the existing A1111 implantation here. It looks like Comfy also uses the same algorithm.
> 
> Could you explain the heuristic used to stretch the sigmas over the steps ?

@blob42 No heuristic at all. I simply took 14.615 and divided it into 32 parts. Each section was rounded up or down according to "precision 3", although I wish I could force it to use "precision 10" for even cleaner results.

@dan4ik94 I can try, although some people will argue with the results. 11 Sigmas over 32 Steps looks nice, but it lacks coherence compared to 32 Sigmas over 32 Steps.

First prompt is from here: https://prompthero.com/prompt/cf5ed5a0881
Second prompt is from here: https://prompthero.com/prompt/1107ce59578
Third prompt is from here: https://prompthero.com/prompt/cef4653ee67

Here is a link to the 4 grids for side by side comparison. I used multiple samplers in different images so you can see better results. 11 Sigmas only performs really well under Heun with complex prompts.

https://imgur.com/a/NQLCD4M

As you can see, Sigmas should be stretched over the amount of steps you use for better prompt coherence.

**Comment by blob42** [comment]
I will do some experiments in a separate branch it should be fairly easy to update the code to dynamically split the sigmas.


> As for the testing, you will not be able to replicate my results. I'm using a lot of custom forked & edited code that I haven't uploaded to a repo yet, along with 2k generation using a 64k resized seed.

You got me curious about this, what do you mean with 2k gen using 64k seed resize ?

**Comment by Koitenshin** [comment]
> I will do some experiments in a separate branch it should be fairly easy to update the code to dynamically split the sigmas.
> 
> > As for the testing, you will not be able to replicate my results. I'm using a lot of custom forked & edited code that I haven't uploaded to a repo yet, along with 2k generation using a 64k resized seed.
> 
> You got me curious about this, what do you mean with 2k gen using 64k seed resize ?

Every single small image on those xyz grids is a 1080x1920 portrait, you can blow them all up on the Imgur album to view them in their entirety.

There's a checkbox labeled 'Extra' next to the Seed on the A1111 interface. On this subpanel you have two options: Resize seed from width & Resize seed from height. I have the options set to 34560 x 61440 (64K, as in 4K Ultra HD, 8K, 16K, etc). The higher you can set this number, the more detail you can draw out of your image. 

I'm talking pure generation, no complicated workflows, inpainting, loras, negative prompts, upscaling, control nets, or whatever else hasn't been thought of yet. Even when A1111 first came out I was generating 1080p (without hires fix) because I modified the source code and fixed the tensor math. I can't remember what I modified but the issue lies in processing.py

**Pull request merged**
