### PR TITLE
batch mask

### PR DESCRIPTION
**Pull request by continue-revolution**

### CODE REVIEW

**Comment by lllyasviel** [comment]
ask @huchenlei to look at if infotext is broken

**Comment by continue-revolution** [comment]
@lllyasviel why do you increment update_unit_counter at https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/extensions-builtin/sd_forge_controlnet/lib_controlnet/controlnet_ui/controlnet_ui_group.py#L1064? Is it necessary?

**Comment by continue-revolution** [comment]
yes infotext is indeed broken and I don't know why

**Comment by lllyasviel** [comment]
update_unit_counter is @huchenlei's codes and I also do not know why

**Comment by lllyasviel** [comment]
merge when necessary after you test it fine

**Comment by continue-revolution** [comment]
Sure. We need @huchenlei to fix infotext.

**Comment by continue-revolution** [comment]
@huchenlei pls directly merge this after you’ve done infotext

**Comment by huchenlei** [comment]
The counter definition has comment explaining why. The batch upload only updates a state, which does not automatically trigger update of UiControlNetUnit. So we need an IOComponent to do that triggering when image is uploaded via batch upload.

**Comment by lllyasviel** [comment]
i revert that commit, please take a look where should also add that trigger and take a look at infotext

**Comment by huchenlei** [comment]
What are the steps I can follow to reproduce the infotext issue? It seems like single image ControlNet generation still works fine.

**Comment by huchenlei** [comment]
Infotext is fixed now. Please verify.

**Comment by lllyasviel** [comment]
I am not online, but any change must ensure that you tested at least sd1.5 with a basic single image canny controlnet
then if works can merge

**Comment by continue-revolution** [comment]
yes it works for me. will merge now

**Pull request merged**
