### PR TITLE
Update FreeU extension for compatibility with FLUX model and add debu…

### PR DESCRIPTION
**Pull request by captainzero93**
note: although I think this is CLOSE, it does not currently seem to be functioning as intended, after feedback and extra testing.

1. Enhanced model channel detection to _work_ with FLUX model structure
2. Added robust error handling and debugging logs
3. Implemented fallback mechanisms for model_channels inference
4. Improved code flexibility to accommodate different model architectures

Note: Further testing with various FLUX model versions and configurations needed.

### CODE REVIEW

**Comment by Melyns** [comment]
Great work! thanks for your contribution

**Comment by captainzero93** [comment]
Sorry for the accidental push of the readme, I got into a pickle

**Comment by DenOfEquity** [comment]
I'm seeing no effect with any model: tried sd1.5 models, sdxl, Q2_K gguf, flux1-dev-bnb-nf4-v2.
reason: `scale` is `None` every time
Tracked it to the `in_channels` path, returning values 4/4/64 for sd/xl/flux, when 320/320/?? is needed. Bypassing that path, sd15 and sdxl work as expected but Flux gets an inferred value of 28311552, which seems *excessive*.
Is freeU applicable to transformer model architectures, or unet only?

**Comment by captainzero93** [comment]
> I'm seeing no effect with any model: tried sd1.5 models, sdxl, Q2_K gguf, flux1-dev-bnb-nf4-v2. reason: `scale` is `None` every time Tracked it to the `in_channels` path, returning values 4/4/64 for sd/xl/flux, when 320/320/?? is needed. Bypassing that path, sd15 and sdxl work as expected but Flux gets an inferred value of 28311552, which seems _excessive_. Is freeU applicable to transformer model architectures, or unet only?

I have reworked the code, attempt it again, I need to look more into if this SHOULD work, at the very least it should no longer stop working with other models

**Comment by captainzero93** [comment]
Looked at FLUX more closely and the paper for freeU added A specialized apply_freeu_to_flux function that attempts to handle FLUX's hybrid architecture.
A flow_matching_scale function that approximates the flow matching principle used in FLUX
Hopefully this works now, I am still testing

**Comment by captainzero93** [comment]
no, it appears the new logic, has not fixed the issue with flux1-dev-bnb-nf4-v2.safetensors at least, I'll have to look into it more I think it's closer and possible, If anyone has an idea of how to fix it please let me know

**Comment by captainzero93** [comment]
until I can find some better documentation, this has a generic attempt at dealing with FLUX, if anyone can see the problem it would be amazing if you'd colab

**Comment by lllyasviel** [comment]
Unfortunately this PR is not correct and cannot be merged. But thanks a lot for considering making a contribution to Forge

**Comment by captainzero93** [comment]
Appreciate it, I will work on it more and try to fix it, thanks for all your hard work @lllyasviel

**Pull request closed without merging**
