### PR TITLE
add distilled cfg to xyz grid

### PR DESCRIPTION
**Pull request by DenOfEquity**
as title, mentioned https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1391

Simple enough that I dare to merge it myself.

### CODE REVIEW

**Comment by lllyasviel** [comment]
give me your discord name

**Comment by DenOfEquity** [comment]
I've never used it, should I sign up?

**Comment by lllyasviel** [comment]
or email

**Comment by DenOfEquity** [comment]
primatemaster@hotmail.com

**Pull request merged**
