### PR TITLE
add support for Hrfix and CN

### PR DESCRIPTION
**Pull request by jetjodh**
## Description

* Fix interop issue of kohya hrfix and CN
* Fixes: https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/95

## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [x] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by jetjodh** [comment]
@huchenlei can you review this?

**Comment by huchenlei** [comment]
Can you add an API test under https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/extensions-builtin/sd_forge_controlnet/tests/web_api/ ?

It can be similar to the test added in https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/754 . Although we cannot enable the test in the CQ, at least we can have a stable way to verify this is working locally and compare test results across versions.

**Comment by jetjodh** [comment]
> Can you add an API test under https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/extensions-builtin/sd_forge_controlnet/tests/web_api/ ?
> 
> It can be similar to the test added in #754 . Although we cannot enable the test in the CQ, at least we can have a stable way to verify this is working locally and compare test results across versions.

Added a test(hopefully works)

**Comment by adde88** [comment]
I tested this patch today several times, on both 1.5, and SDXL models, with HRfix and CN. The errors are not there anymore, and it seems to work. Thought i'd give some feedback :)

**Pull request closed without merging**
