### PR TITLE
Add New Controlnet Nromal preprocesser Depth_fm

### PR DESCRIPTION
**Pull request by sdbds**
image

https://github.com/CompVis/depth-fm

Host depth_fm as a python package dependency

### CODE REVIEW

**Review by huchenlei — COMMENTED** [review]
We should probably stop adding new entries to the legacy preprocessor file. Can you make adjustment to follow the new preprocessor guideline?

https://github.com/lllyasviel/stable-diffusion-webui-forge#add-a-preprocessor

**Comment by sdbds** [comment]
> We should probably stop adding new entries to the legacy preprocessor file. Can you make adjustment to follow the new preprocessor guideline?
> 
> https://github.com/lllyasviel/stable-diffusion-webui-forge#add-a-preprocessor

OK,  ill add it outside.

**Comment by sdbds** [comment]
> We should probably stop adding new entries to the legacy preprocessor file. Can you make adjustment to follow the new preprocessor guideline?
> 
> https://github.com/lllyasviel/stable-diffusion-webui-forge#add-a-preprocessor

Because the author of the original depth_fm wrote model load_state_dict in the source code, it is difficult to load it using an external mod patcher, and after I tried it, I found that the part of the VRAM management is not easy to unload outside of the preprocessor, which is not effective, so I would suggest to put it in inside instead.

**Comment by huchenlei** [comment]
> > We should probably stop adding new entries to the legacy preprocessor file. Can you make adjustment to follow the new preprocessor guideline?
> > https://github.com/lllyasviel/stable-diffusion-webui-forge#add-a-preprocessor
> 
> Because the author of the original depth_fm wrote model load_state_dict in the source code, it is difficult to load it using an external mod patcher, and after I tried it, I found that the part of the VRAM management is not easy to unload outside of the preprocessor, which is not effective, so I would suggest to put it in inside instead.

I think @lllyasviel implemented very aggressive memory management system that hijacks every torch.nn.Module creation and unload them when necessary. Manual unloading in preprocessor code is no longer necessary.

**Comment by kagevazquez** [comment]
https://github.com/lpiccinelli-eth/UniDepth > This is more accurate than depth_anything and depth_fm.

**Comment by huchenlei** [comment]
This can probably be hosted in a separate repo. Closing for now.

**Pull request closed without merging**
