### PR TITLE
Add back ControlNet HR option

### PR DESCRIPTION
**Pull request by huchenlei**
## Description
Requested in https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/70

## Checklist:

- [ ] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [ ] I have performed a self-review of my own code
- [ ] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ ] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by lllyasviel** [comment]
do not add ui codes to kernel supported_controlnet.py

**Comment by huchenlei** [comment]
> do not add ui codes to kernel supported_controlnet.py

Where do you think is an appropriate place for that enum? If we leave it in UI code, it will cause import issue when controlnet extension is disabled.

**Comment by lllyasviel** [comment]
> > do not add ui codes to kernel supported_controlnet.py
> 
> Where do you think is an appropriate place for that enum? If we leave it in UI code, it will cause import issue when controlnet extension is disabled.

that is expected

**Comment by lllyasviel** [comment]
i am going to take a look

**Comment by lllyasviel** [comment]
I finished
but infotext need this so you can add that

merge after you test fine

**Review by lllyasviel — APPROVED** [review]

**Pull request merged**
