### PR TITLE
Respect send seed

### PR DESCRIPTION
**Pull request by wcole3**
Correction to #2349, fields to paste needs to be filtered for Seed wrt `send_seed` config option.  Added logic for the `send_size` option too, but it seems less likely that someone wouldn't want that to be True.

Might be worth a discussion if the `send_seed` option should be False by default, but idk what the impact of changing the config.json and associated `shared_option` code would be.  Thoughts very welcome.

#2359

### CODE REVIEW

**Comment by DenOfEquity** [comment]
These options will also be used by PNG Info send to, and the paste button. So they should not default to False. (These are the places `source_text_component` was set up previously.)
The setup for this pasting is done on UI creation, so the *send_seed* and *send_size* options (in *shared_options.py*) should have `.needs_reload_ui()` added.
Typo in `dont_paste_fileds`.
There's some odd behaviour after repeated sends, width/height can alternate between values for a cycle or two. (send, change width/height, send again). Changing line 182 to `elif` seems to fix - avoids repeated setting of components.

**Comment by DenOfEquity** [comment]
Thanks.
The elif path could be used by extensions, safer to leave it.
What is Results tab?

**Comment by wcole3** [comment]
Understood, makes sense.  Sorry "Results" panel; i,e. `OutputPanel`

**Comment by wcole3** [comment]
Found another undesirable behavior, the information pasted always comes from the last generated image, which might not correspond to the image a user is trying to paste.  You can observe this by generating an image, pasting to img2img (should work), changing some of the generation parameters, running img2img, and then trying to paste the original image generated in txt2img again.  The information that gets sent is from the last img2img generation.

I'm pretty sure it's due to how I hooked into the button that updates the generation_info, I need to find a way to get that info from the image (which does still get pasted correctly) directly.  If I can't figure it out tomorrow, I'll put open a revert PR.

**Comment by wcole3** [comment]
I believe that last commit addresses the issue, but keeping this in draft to do more testing tomorrow

**Comment by ChooChoo38** [comment]
In addition to sending the seed, it's also turning off scripts and appending LoRA's to the prompt in a case where you might not want it to. Examples:

1) I have the Ultimate SD Upscale script turned on in the img2img tab. Going to txt2img and clicking "Send image and generation parameters to img2img tab" sets "Script" to none in the img2img tab, disabling it. I have to re-enable it every time.

2) I add a LoRA via the "Add network to prompt" dropdown. This appends it to the prompt when you generate so you don't have to manually add it to the prompt text box yourself. However, when I send the image to the img2img tab, it automatically adds the LoRA text to the prompt itself. It shouldn't do that in this case, given I've already got it enabled in the dropdown.

**Comment by DenOfEquity** [comment]
The more I think about this (+ previous PR), the more I think it's not ideal. It copies all settings, including those of extensions, so the likelihood of unwanted overwriting is high. It also always copies settings between img2img <-> inpaint, when that is probably unnecessary (already set) or especially likely to be undesirable (user has adjusted).
If full settings transfer is wanted, it can be done as a two stage process, via PNG Info, anyway. So currently I think reverting the buttons to have the original lighter touch is best. (doesn't need a new PR btw, I can Revert the previous one.)

**Comment by wcole3** [comment]
Sounds good to me.

**Pull request closed without merging**
