### PR TITLE
Bug fix override settings sdapi

### PR DESCRIPTION
**Pull request by vaskers5**

### CODE REVIEW

**Comment by vaskers5** [comment]
Fixed this issue:

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1940

**Comment by altoiddealer** [comment]
Ehh... I was excited about this PR, but I don't think this is the correct fix.

What this does is makes it so that an `override_settings` dict will modify the current settings - a persistent change.

Historically, the purpose of `override_settings` is to only temporarily modify the settings for the current request ("Override the current settings").

**Comment by vaskers5** [comment]
got  u, I will try to fix it in the right way

**Comment by altoiddealer** [comment]
@vaskers5 I'm sorry but I was feeling a bit ambitious tonight, and was able to solve this.

I also made an additional improvement regarding the handling of modules via `options` and `override_settings`

https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2027

**Comment by DenOfEquity** [comment]
closed as replaced by #2027

**Pull request closed without merging**
