### PR TITLE
Add xyz plot feature to "sd_forge_freeu"

### PR DESCRIPTION
**Pull request by sJrx233S7UMo**
## Description

This PR adds functionality for X/Y/Z plot to FreeU Integrated (sd_forge_freeu).

## Checklist:

- [ ] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [ ] I have performed a self-review of my own code
- [ ] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ ] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by lllyasviel** [comment]
I am willing to merge this but the codes for freeu is not only an extension but also more or less a tutorial about how to make a Forge extension.

Adding more things will make that code lengthy and less clear how Forge’s unet patcher works

**Comment by strawberrymelonpanda** [comment]
> the codes for freeu is not only an extension but also more or less a tutorial about how to make a Forge extension.

I think there'd be a lot of value in splitting the tutorial off from the functionality.  The tutorial could live in either the wiki, or an examples folder.

**Comment by sJrx233S7UMo** [comment]
Thank you for the review.

**Review by huchenlei — APPROVED** [review]
LGTM. I am going to merge this into dev2 for now.

**Pull request merged**
