### PR TITLE
fix sampler device

### PR DESCRIPTION
**Pull request by continue-revolution**

### CODE REVIEW

**Comment by continue-revolution** [comment]
@MUTED64
try this PR and see if it works

**Comment by MUTED64** [comment]
Still not working. [Traceback](https://pastebin.ubuntu.com/p/srhTvS8TVq/)

**Comment by continue-revolution** [comment]
I don't understand why. With SD15 or SDXL, with or without this pr, I cannot reproduce your problem. What's your device setup?

**Comment by MUTED64** [comment]
```
Total VRAM 4096 MB, total RAM 16225 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --always-normal-vram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1050 : native
VAE dtype: torch.float32
CUDA Stream Activated:  False
Using pytorch cross attention
Model: Pony Diffusion V6 XL (SDXL)
```
I can generate successfully with ef35383, but not 72139b0.

**Comment by continue-revolution** [comment]
how about now? if this time it cannot work then I cannot help.

**Review by lllyasviel — APPROVED** [review]

**Comment by MUTED64** [comment]
> how about now? if this time it cannot work then I cannot help.

420013e76b3c5474d90bd8c98adbbad589cff504 success. Thank you for your patient and timely responses.

**Comment by lllyasviel** [comment]
but still have some potential problems to i2i or inpaint and i will review that later

**Comment by lllyasviel** [comment]
hi we are going to close PRs before forge's recent major revision
if we missed some important PRs, please consider reopen (if that is not already on our todo list

**Pull request closed without merging**
